swagger: "2.0"
info:
  description: "This is a crypto project"
  version: "1.0.0"
  title: "crypto"
host: "localhost:8080"
basePath: "/v1"
schemes:
  - "http"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /users/:
    post:
      summary: "Register new user"
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "User has been registered"
          schema:
            $ref: "#/definitions/User"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/login:
    post:
      summary: "Login"
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "User logined"
          schema:
            type: string
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/leaderboard:
    get:
      security:
      - Bearer: []
      summary: "Get top list of users"
      responses:
        200:
          description: "Ok"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}/status:
    get:
      security:
      - Bearer: []
      summary: "Get user by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    delete:
      security:
      - Bearer: []
      summary: "Delete user by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: "User deleted"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{user_id}/task/complete:
    post:
      security:
      - Bearer: []
      summary: "Completion user's task"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - in: body
          name: task
          required: true
          schema:
            $ref: "#/definitions/NewTask"
      responses:
        201:
          description: "User's task was completed"
          schema:
            $ref: "#/definitions/Task"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{user_id}/referrer:
    post:
      security:
      - Bearer: []
      summary: "Refferrer"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - in: body
          name: refferer
          required: true
          schema:
            $ref: "#/definitions/NewReferrer"
      responses:
        201:
          description: "User's task was completed"
          schema:
            $ref: "#/definitions/Referrer"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      password:
        type: string
      balance:
        type: integer
  NewUser:
    type: object
    properties:
      email:
        type: string
        x-go-custom-tag: "validate:\"required\""
      password:
        type: string
        x-go-custom-tag: "validate:\"required\""
  Task:
    type: object
    properties:
      id:
        type: integer
      user_id:
        type: integer
      name:
        type: string
  NewTask:
    type: object
    properties:
      name:
        type: string
        x-go-custom-tag: "validate:\"required\""
  Referrer:
    type: object
    properties:
      id:
        type: integer
      user_id:
        type: integer
      referrer:
        type: string
  NewReferrer:
    type: object
    properties:
      referrer:
        type: string
        x-go-custom-tag: "validate:\"required\""
  ErrorResponse:
    title: ErrorResponse
    description: Общая ошибка
    allOf:
      - properties:
          error:
            type: object
            properties:
              message:
                description: Message
                type: string
