// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a crypto project",
    "title": "crypto",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/users/": {
      "post": {
        "summary": "Register new user",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewUser"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User has been registered",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/leaderboard": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Get top list of users",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "summary": "Login",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewUser"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User logined",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Delete user by ID",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "User deleted"
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}/balance": {
      "patch": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Update balance",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "balance",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserBalance"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Update balance updated",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}/status": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Get user by ID",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "User not found"
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{user_id}/referrer": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Refferrer",
        "parameters": [
          {
            "type": "integer",
            "name": "user_id",
            "in": "path",
            "required": true
          },
          {
            "name": "refferer",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewReferrer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User's task was completed",
            "schema": {
              "$ref": "#/definitions/Referrer"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{user_id}/task/complete": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Completion user's task",
        "parameters": [
          {
            "type": "integer",
            "name": "user_id",
            "in": "path",
            "required": true
          },
          {
            "name": "task",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewTask"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User's task was completed",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "description": "Общая ошибка",
      "title": "ErrorResponse",
      "allOf": [
        {
          "properties": {
            "error": {
              "type": "object",
              "properties": {
                "message": {
                  "description": "Message",
                  "type": "string"
                }
              }
            }
          }
        }
      ]
    },
    "NewReferrer": {
      "type": "object",
      "properties": {
        "referrer": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "NewTask": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "NewUser": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        },
        "password": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "Referrer": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "referrer": {
          "type": "string"
        },
        "user_id": {
          "type": "integer"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "user_id": {
          "type": "integer"
        }
      }
    },
    "UpdateUserBalance": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "integer",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "balance": {
          "type": "integer"
        },
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "password": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a crypto project",
    "title": "crypto",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/users/": {
      "post": {
        "summary": "Register new user",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewUser"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User has been registered",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/leaderboard": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Get top list of users",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "summary": "Login",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewUser"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User logined",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Delete user by ID",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "User deleted"
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}/balance": {
      "patch": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Update balance",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "balance",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserBalance"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Update balance updated",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}/status": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Get user by ID",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "User not found"
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{user_id}/referrer": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Refferrer",
        "parameters": [
          {
            "type": "integer",
            "name": "user_id",
            "in": "path",
            "required": true
          },
          {
            "name": "refferer",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewReferrer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User's task was completed",
            "schema": {
              "$ref": "#/definitions/Referrer"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{user_id}/task/complete": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Completion user's task",
        "parameters": [
          {
            "type": "integer",
            "name": "user_id",
            "in": "path",
            "required": true
          },
          {
            "name": "task",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewTask"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User's task was completed",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          },
          "default": {
            "description": "Общая ошибка",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "description": "Общая ошибка",
      "title": "ErrorResponse",
      "allOf": [
        {
          "properties": {
            "error": {
              "type": "object",
              "properties": {
                "message": {
                  "description": "Message",
                  "type": "string"
                }
              }
            }
          }
        }
      ]
    },
    "ErrorResponseAO0Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "Message",
          "type": "string"
        }
      }
    },
    "NewReferrer": {
      "type": "object",
      "properties": {
        "referrer": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "NewTask": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "NewUser": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        },
        "password": {
          "type": "string",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "Referrer": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "referrer": {
          "type": "string"
        },
        "user_id": {
          "type": "integer"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "user_id": {
          "type": "integer"
        }
      }
    },
    "UpdateUserBalance": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "integer",
          "x-go-custom-tag": "validate:\"required\""
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "balance": {
          "type": "integer"
        },
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "password": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
