// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewReferrer new referrer
//
// swagger:model NewReferrer
type NewReferrer struct {

	// referrer
	Referrer string `json:"referrer,omitempty" validate:"required"`
}

// Validate validates this new referrer
func (m *NewReferrer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new referrer based on context it is used
func (m *NewReferrer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewReferrer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewReferrer) UnmarshalBinary(b []byte) error {
	var res NewReferrer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
