// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTask new task
//
// swagger:model NewTask
type NewTask struct {

	// name
	Name string `json:"name,omitempty" validate:"required"`
}

// Validate validates this new task
func (m *NewTask) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new task based on context it is used
func (m *NewTask) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewTask) UnmarshalBinary(b []byte) error {
	var res NewTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
