// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Referrer referrer
//
// swagger:model Referrer
type Referrer struct {

	// id
	ID int64 `json:"id,omitempty"`

	// referrer
	Referrer string `json:"referrer,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this referrer
func (m *Referrer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this referrer based on context it is used
func (m *Referrer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Referrer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Referrer) UnmarshalBinary(b []byte) error {
	var res Referrer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
