// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"main/models"
)

// GetUsersIDStatusOKCode is the HTTP code returned for type GetUsersIDStatusOK
const GetUsersIDStatusOKCode int = 200

/*
GetUsersIDStatusOK Ok

swagger:response getUsersIdStatusOK
*/
type GetUsersIDStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetUsersIDStatusOK creates GetUsersIDStatusOK with default headers values
func NewGetUsersIDStatusOK() *GetUsersIDStatusOK {

	return &GetUsersIDStatusOK{}
}

// WithPayload adds the payload to the get users Id status o k response
func (o *GetUsersIDStatusOK) WithPayload(payload *models.User) *GetUsersIDStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id status o k response
func (o *GetUsersIDStatusOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersIDStatusNotFoundCode is the HTTP code returned for type GetUsersIDStatusNotFound
const GetUsersIDStatusNotFoundCode int = 404

/*
GetUsersIDStatusNotFound User not found

swagger:response getUsersIdStatusNotFound
*/
type GetUsersIDStatusNotFound struct {
}

// NewGetUsersIDStatusNotFound creates GetUsersIDStatusNotFound with default headers values
func NewGetUsersIDStatusNotFound() *GetUsersIDStatusNotFound {

	return &GetUsersIDStatusNotFound{}
}

// WriteResponse to the client
func (o *GetUsersIDStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*
GetUsersIDStatusDefault Общая ошибка

swagger:response getUsersIdStatusDefault
*/
type GetUsersIDStatusDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetUsersIDStatusDefault creates GetUsersIDStatusDefault with default headers values
func NewGetUsersIDStatusDefault(code int) *GetUsersIDStatusDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUsersIDStatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get users ID status default response
func (o *GetUsersIDStatusDefault) WithStatusCode(code int) *GetUsersIDStatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get users ID status default response
func (o *GetUsersIDStatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get users ID status default response
func (o *GetUsersIDStatusDefault) WithPayload(payload *models.ErrorResponse) *GetUsersIDStatusDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users ID status default response
func (o *GetUsersIDStatusDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDStatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
