// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"main/internal/models"
)

// GetUsersLeaderboardOKCode is the HTTP code returned for type GetUsersLeaderboardOK
const GetUsersLeaderboardOKCode int = 200

/*
GetUsersLeaderboardOK Ok

swagger:response getUsersLeaderboardOK
*/
type GetUsersLeaderboardOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewGetUsersLeaderboardOK creates GetUsersLeaderboardOK with default headers values
func NewGetUsersLeaderboardOK() *GetUsersLeaderboardOK {

	return &GetUsersLeaderboardOK{}
}

// WithPayload adds the payload to the get users leaderboard o k response
func (o *GetUsersLeaderboardOK) WithPayload(payload []*models.User) *GetUsersLeaderboardOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users leaderboard o k response
func (o *GetUsersLeaderboardOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersLeaderboardOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetUsersLeaderboardDefault Общая ошибка

swagger:response getUsersLeaderboardDefault
*/
type GetUsersLeaderboardDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetUsersLeaderboardDefault creates GetUsersLeaderboardDefault with default headers values
func NewGetUsersLeaderboardDefault(code int) *GetUsersLeaderboardDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUsersLeaderboardDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get users leaderboard default response
func (o *GetUsersLeaderboardDefault) WithStatusCode(code int) *GetUsersLeaderboardDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get users leaderboard default response
func (o *GetUsersLeaderboardDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get users leaderboard default response
func (o *GetUsersLeaderboardDefault) WithPayload(payload *models.ErrorResponse) *GetUsersLeaderboardDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users leaderboard default response
func (o *GetUsersLeaderboardDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersLeaderboardDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
