// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUsersIDStatusHandlerFunc turns a function with the right signature into a get users ID status handler
type GetUsersIDStatusHandlerFunc func(GetUsersIDStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUsersIDStatusHandlerFunc) Handle(params GetUsersIDStatusParams) middleware.Responder {
	return fn(params)
}

// GetUsersIDStatusHandler interface for that can handle valid get users ID status params
type GetUsersIDStatusHandler interface {
	Handle(GetUsersIDStatusParams) middleware.Responder
}

// NewGetUsersIDStatus creates a new http.Handler for the get users ID status operation
func NewGetUsersIDStatus(ctx *middleware.Context, handler GetUsersIDStatusHandler) *GetUsersIDStatus {
	return &GetUsersIDStatus{Context: ctx, Handler: handler}
}

/*
	GetUsersIDStatus swagger:route GET /users/{id}/status getUsersIdStatus

Get user by ID
*/
type GetUsersIDStatus struct {
	Context *middleware.Context
	Handler GetUsersIDStatusHandler
}

func (o *GetUsersIDStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUsersIDStatusParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
