// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUsersLeaderboardHandlerFunc turns a function with the right signature into a get users leaderboard handler
type GetUsersLeaderboardHandlerFunc func(GetUsersLeaderboardParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUsersLeaderboardHandlerFunc) Handle(params GetUsersLeaderboardParams) middleware.Responder {
	return fn(params)
}

// GetUsersLeaderboardHandler interface for that can handle valid get users leaderboard params
type GetUsersLeaderboardHandler interface {
	Handle(GetUsersLeaderboardParams) middleware.Responder
}

// NewGetUsersLeaderboard creates a new http.Handler for the get users leaderboard operation
func NewGetUsersLeaderboard(ctx *middleware.Context, handler GetUsersLeaderboardHandler) *GetUsersLeaderboard {
	return &GetUsersLeaderboard{Context: ctx, Handler: handler}
}

/*
	GetUsersLeaderboard swagger:route GET /users/leaderboard getUsersLeaderboard

Get top list of users
*/
type GetUsersLeaderboard struct {
	Context *middleware.Context
	Handler GetUsersLeaderboardHandler
}

func (o *GetUsersLeaderboard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUsersLeaderboardParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
