// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchUsersIDBalanceHandlerFunc turns a function with the right signature into a patch users ID balance handler
type PatchUsersIDBalanceHandlerFunc func(PatchUsersIDBalanceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUsersIDBalanceHandlerFunc) Handle(params PatchUsersIDBalanceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchUsersIDBalanceHandler interface for that can handle valid patch users ID balance params
type PatchUsersIDBalanceHandler interface {
	Handle(PatchUsersIDBalanceParams, interface{}) middleware.Responder
}

// NewPatchUsersIDBalance creates a new http.Handler for the patch users ID balance operation
func NewPatchUsersIDBalance(ctx *middleware.Context, handler PatchUsersIDBalanceHandler) *PatchUsersIDBalance {
	return &PatchUsersIDBalance{Context: ctx, Handler: handler}
}

/*
	PatchUsersIDBalance swagger:route PATCH /users/{id}/balance patchUsersIdBalance

Update balance
*/
type PatchUsersIDBalance struct {
	Context *middleware.Context
	Handler PatchUsersIDBalanceHandler
}

func (o *PatchUsersIDBalance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchUsersIDBalanceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
