// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"main/internal/models"
)

// PostUsersUserIDReferrerCreatedCode is the HTTP code returned for type PostUsersUserIDReferrerCreated
const PostUsersUserIDReferrerCreatedCode int = 201

/*
PostUsersUserIDReferrerCreated User's task was completed

swagger:response postUsersUserIdReferrerCreated
*/
type PostUsersUserIDReferrerCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Referrer `json:"body,omitempty"`
}

// NewPostUsersUserIDReferrerCreated creates PostUsersUserIDReferrerCreated with default headers values
func NewPostUsersUserIDReferrerCreated() *PostUsersUserIDReferrerCreated {

	return &PostUsersUserIDReferrerCreated{}
}

// WithPayload adds the payload to the post users user Id referrer created response
func (o *PostUsersUserIDReferrerCreated) WithPayload(payload *models.Referrer) *PostUsersUserIDReferrerCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users user Id referrer created response
func (o *PostUsersUserIDReferrerCreated) SetPayload(payload *models.Referrer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersUserIDReferrerCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostUsersUserIDReferrerDefault Общая ошибка

swagger:response postUsersUserIdReferrerDefault
*/
type PostUsersUserIDReferrerDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostUsersUserIDReferrerDefault creates PostUsersUserIDReferrerDefault with default headers values
func NewPostUsersUserIDReferrerDefault(code int) *PostUsersUserIDReferrerDefault {
	if code <= 0 {
		code = 500
	}

	return &PostUsersUserIDReferrerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post users user ID referrer default response
func (o *PostUsersUserIDReferrerDefault) WithStatusCode(code int) *PostUsersUserIDReferrerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post users user ID referrer default response
func (o *PostUsersUserIDReferrerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post users user ID referrer default response
func (o *PostUsersUserIDReferrerDefault) WithPayload(payload *models.ErrorResponse) *PostUsersUserIDReferrerDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users user ID referrer default response
func (o *PostUsersUserIDReferrerDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersUserIDReferrerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
