// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUsersUserIDTaskCompleteHandlerFunc turns a function with the right signature into a post users user ID task complete handler
type PostUsersUserIDTaskCompleteHandlerFunc func(PostUsersUserIDTaskCompleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersUserIDTaskCompleteHandlerFunc) Handle(params PostUsersUserIDTaskCompleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUsersUserIDTaskCompleteHandler interface for that can handle valid post users user ID task complete params
type PostUsersUserIDTaskCompleteHandler interface {
	Handle(PostUsersUserIDTaskCompleteParams, interface{}) middleware.Responder
}

// NewPostUsersUserIDTaskComplete creates a new http.Handler for the post users user ID task complete operation
func NewPostUsersUserIDTaskComplete(ctx *middleware.Context, handler PostUsersUserIDTaskCompleteHandler) *PostUsersUserIDTaskComplete {
	return &PostUsersUserIDTaskComplete{Context: ctx, Handler: handler}
}

/*
	PostUsersUserIDTaskComplete swagger:route POST /users/{user_id}/task/complete postUsersUserIdTaskComplete

Completion user's task
*/
type PostUsersUserIDTaskComplete struct {
	Context *middleware.Context
	Handler PostUsersUserIDTaskCompleteHandler
}

func (o *PostUsersUserIDTaskComplete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersUserIDTaskCompleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
