// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUsersUserIDReferrerHandlerFunc turns a function with the right signature into a post users user ID referrer handler
type PostUsersUserIDReferrerHandlerFunc func(PostUsersUserIDReferrerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersUserIDReferrerHandlerFunc) Handle(params PostUsersUserIDReferrerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUsersUserIDReferrerHandler interface for that can handle valid post users user ID referrer params
type PostUsersUserIDReferrerHandler interface {
	Handle(PostUsersUserIDReferrerParams, interface{}) middleware.Responder
}

// NewPostUsersUserIDReferrer creates a new http.Handler for the post users user ID referrer operation
func NewPostUsersUserIDReferrer(ctx *middleware.Context, handler PostUsersUserIDReferrerHandler) *PostUsersUserIDReferrer {
	return &PostUsersUserIDReferrer{Context: ctx, Handler: handler}
}

/*
	PostUsersUserIDReferrer swagger:route POST /users/{user_id}/referrer postUsersUserIdReferrer

Refferrer
*/
type PostUsersUserIDReferrer struct {
	Context *middleware.Context
	Handler PostUsersUserIDReferrerHandler
}

func (o *PostUsersUserIDReferrer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersUserIDReferrerParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
