// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUsersIDReferrerHandlerFunc turns a function with the right signature into a post users ID referrer handler
type PostUsersIDReferrerHandlerFunc func(PostUsersIDReferrerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersIDReferrerHandlerFunc) Handle(params PostUsersIDReferrerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUsersIDReferrerHandler interface for that can handle valid post users ID referrer params
type PostUsersIDReferrerHandler interface {
	Handle(PostUsersIDReferrerParams, interface{}) middleware.Responder
}

// NewPostUsersIDReferrer creates a new http.Handler for the post users ID referrer operation
func NewPostUsersIDReferrer(ctx *middleware.Context, handler PostUsersIDReferrerHandler) *PostUsersIDReferrer {
	return &PostUsersIDReferrer{Context: ctx, Handler: handler}
}

/*
	PostUsersIDReferrer swagger:route POST /users/{id}/referrer postUsersIdReferrer

Refferrer
*/
type PostUsersIDReferrer struct {
	Context *middleware.Context
	Handler PostUsersIDReferrerHandler
}

func (o *PostUsersIDReferrer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersIDReferrerParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
